### PR TITLE
Migrate `proppy-preact` and `proppy-frint-react` to TypeScript

### PR DESCRIPTION
**Pull request by chimon2000**
I did not see any unit tests but am more than willing to add them.  This is a first pass.

Relates to #5

### CODE REVIEW

**Comment by fahad19** [comment]
This is absolutely brilliant! Thanks for the help, @chimon2000! Didn't expect to receive any help regarding #5 :D 

The Travis-CI setup doesn't actually have `npm run dist` in it, which involves bundling using Webpack: https://github.com/fahad19/proppy/blob/master/.travis.yml#L6

Could you please double check if the dists are still being generated well running `npm run dist` from root?

---

@jchn: could you kindly check if this PR is in line with your changes in #22?

**Comment by jchn** [comment]
Did a quick check and It seems that the `parentProps` are missing in the render function of `ProppySubscription`, if I merge `this.state.proppyProps` with `props.parentProps` in the render function of `ProppySubscription` it works :)

```ts
  public render(props) {
    return props.children[0](Object.assign(
      {}, 
      this.state.proppyProps, 
      props.parentProps
    ));
  }
```

**Comment by chimon2000** [comment]
Will do @fahad19

**Comment by chimon2000** [comment]
@fahad19 verified

**Comment by fahad19** [comment]
@chimon2000: awesome! I will check it when home later today and merge and release it :)

Tests are welcome too, but they can definitely happen after the merge of this PR. otherwise it risks you to handle conflicts in near future.

**Comment by fahad19** [comment]
Released as v1.2.4: https://github.com/fahad19/proppy/releases/tag/v1.2.4

Thanks again for your contribution!

For further continuation, I have created #24 (for dropping Babel/ESLint) for keeping track.

**Pull request merged**
