### PR TITLE
use ProppyContext's Provider for ProppyProvider (#35) and unit-tests for preact

### LINKED ISSUE #35: Consumer used without Provider
I am using preact (in parcel) and getting this warning whenever I compose an HOC. I apologize, in advance, if this issue belongs in another queue, but it's a bit hard to track down.

```
Consumer used without Provider
```

The HOC still works fine, and it's not app-breaking, just hoping I am using it right and (I am new to preact & proppy, coming from recompose and react.)

Here is my 1-file example:

```js
import { h, render } from 'preact'
import { compose, withState, withHandlers } from 'proppy'
import { ProppyProvider, attach } from 'proppy-preact'

const P = compose(
  withState('counter', 'setCounter', 0),
  withHandlers({
    increment: ({ counter, setCounter }) => e => setCounter(counter + 1),
    decrement: ({ counter, setCounter }) => e => setCounter(counter - 1)
  })
)

const PageHome = attach(P)( ({ increment, decrement, counter }) => (
  <div>
    <button onClick={decrement}>-</button>
    {counter}
    <button onClick={increment}>+</button>
  </div>
))

// global app-state
const providers = {
  foo: false,
  bar: true
}

const Index = () => (
  <ProppyProvider providers={providers}>
    <PageHome />
  </ProppyProvider>
)

render(<Index />, document.getElementById('app'))
```

### PR DESCRIPTION
**Pull request by konsumer**
use ProppyContext's Provider for ProppyProvider

### CODE REVIEW

**Comment by konsumer** [comment]
I started out trying to resolve #35 , but my solution didn't work. In the process, I got test-parity with react, so I'm going to stop there for now.

**Comment by konsumer** [comment]
Seems good on both counts, after last commit. Tests pass & no context-warnings.

**Comment by fahad19** [comment]
@konsumer: thanks for the PR! 🎉 

Looked good from PR-level, but build is now failing on `master` :( 

https://travis-ci.org/fahad19/proppy/builds/440019708

**Comment by fahad19** [comment]
Build passing now. But still has warnings:

```
$ (cd ./packages/proppy-preact/ && npm test)

> proppy-preact@1.2.6 test /Users/FHeylaal/Repos/proppy/packages/proppy-preact
> ../../node_modules/.bin/jest --

 PASS  src/attach.spec.tsx
  ● Console

    console.warn node_modules/preact-context/dist/cjs/context.js:32
      Consumer used without a Provider
    console.warn node_modules/preact-context/dist/cjs/context.js:32
      Consumer used without a Provider
    console.warn node_modules/preact-context/dist/cjs/context.js:32
      Consumer used without a Provider
    console.warn node_modules/preact-context/dist/cjs/context.js:32
      Consumer used without a Provider
    console.warn node_modules/preact-context/dist/cjs/context.js:32
      Consumer used without a Provider

 PASS  src/index.spec.ts

Test Suites: 2 passed, 2 total
Tests:       7 passed, 7 total
Snapshots:   0 total
Time:        1.85s, estimated 2s
Ran all test suites.
```

**Comment by konsumer** [comment]
Hmm, yeh, I think I need to take another look. I'm not quite sure I'm even testing the right things. I tried to pattern it after the react tests, but I think context just works a bit different with preact. I will have another look, soon.

**Pull request merged**
